/**
 * Canonical flat list of every documentation page, mirroring the sidebar
 * order. Single source of truth shared by the prev/next pagination and the
 * search index so both always cover the full docs navigation.
 */
export type DocsRoute = {
  href: string;
  label: string;
  hint?: string;
};

export const DOCS_ROUTES: DocsRoute[] = [
  { href: "/quick-start", label: "Quick Start", hint: "Shortest path to a themed app" },
  { href: "/get-started", label: "Get Started", hint: "Put it in your app" },
  { href: "/core-concepts", label: "Core Concepts", hint: "Families, tokens, runtime" },
  { href: "/tokens", label: "Tokens & Typography", hint: "Every semantic path" },
  { href: "/tokens/code", label: "Code Tokens", hint: "Syntax highlighting tokens" },
  { href: "/choose-package", label: "Which package?", hint: "Install the right thing" },
  { href: "/custom-themes", label: "Custom Themes", hint: "Define, generate, validate" },
  { href: "/scoped-theme", label: "Scoped Theme", hint: "Theme islands" },
  { href: "/sunrise-sunset", label: "Sunrise & Sunset", hint: "Solar-time switching" },
  { href: "/migration", label: "Migration", hint: "Move from older setups" },
  { href: "/presets/default", label: "Default Presets", hint: "Nine signature families" },
  { href: "/presets/brand", label: "Brand Presets", hint: "Real-world palettes" },
  { href: "/zero-flash", label: "Zero Flash", hint: "SSR-first, no flicker" },
  { href: "/no-flash-ssr", label: "No Flash SSR", hint: "Vue, Svelte, Solid & SPAs" },
  { href: "/animation", label: "Animation & Transition", hint: "Live transition lab" },
  { href: "/advanced-features", label: "Advanced Features", hint: "Scopes, history, plugins" },
  { href: "/custom-scrollbar", label: "Custom Scrollbar", hint: "Theme-aware overlay" },
  { href: "/theme-inspector", label: "Theme Inspector", hint: "Inspect the live theme" },
  { href: "/architecture", label: "Architecture", hint: "How it fits together" },
  { href: "/persistence", label: "Persistence", hint: "Survive reloads" },
  { href: "/multi-window-sync", label: "Multi-Window Sync", hint: "Sync across tabs" },
  { href: "/token-resolution", label: "Token Resolution", hint: "How tokens resolve" },
  { href: "/plugins", label: "Plugins", hint: "Extend the runtime" },
  { href: "/dom-adapters", label: "DOM Adapters", hint: "Apply themes to elements" },
  { href: "/vanilla", label: "Framework-Free", hint: "No framework required" },
  { href: "/vite-plugin", label: "Vite Plugin", hint: "Zero-config builds" },
  { href: "/adapters", label: "Adapters", hint: "Bridge to UI libraries" },
  { href: "/libraries", label: "Libraries", hint: "Library integrations" },
  { href: "/libraries/shadcn", label: "shadcn/ui" },
  { href: "/libraries/bootstrap", label: "Bootstrap" },
  { href: "/libraries/daisyui", label: "daisyUI" },
  { href: "/libraries/open-props", label: "Open Props" },
  { href: "/libraries/mui", label: "Material UI" },
  { href: "/libraries/chakra", label: "Chakra UI" },
  { href: "/libraries/antd", label: "Ant Design" },
  { href: "/libraries/mantine", label: "Mantine" },
  { href: "/libraries/unocss", label: "UnoCSS" },
  { href: "/framework-guides", label: "Framework Guides", hint: "Your stack, deeper" },
  { href: "/framework-guides/react", label: "React" },
  { href: "/framework-guides/next", label: "Next.js" },
  { href: "/framework-guides/vue", label: "Vue 3" },
  { href: "/framework-guides/svelte", label: "Svelte 5" },
  { href: "/framework-guides/solid", label: "Solid" },
  { href: "/framework-guides/angular", label: "Angular" },
  { href: "/framework-guides/web", label: "Web Components" },
  { href: "/framework-guides/tailwind", label: "Tailwind CSS" },
  { href: "/framework-guides/astro", label: "Astro" },
  { href: "/framework-guides/nuxt", label: "Nuxt" },
  { href: "/framework-guides/remix", label: "Remix" },
  { href: "/playground", label: "Playground", hint: "Try it yourself" },
  { href: "/theme-studio", label: "Theme Studio", hint: "Generate from a seed" },
  { href: "/accessibility", label: "Accessibility", hint: "WCAG contrast, CVD" },
  { href: "/showcase", label: "Showcase", hint: "Built with Theme Kit" },
  { href: "/cli", label: "CLI", hint: "Command-line toolkit" },
  { href: "/cli/installation", label: "Installation" },
  { href: "/cli/quickstart", label: "Quick Start" },
  { href: "/cli/generate", label: "generate" },
  { href: "/cli/validate", label: "validate" },
  { href: "/cli/inspect", label: "inspect" },
  { href: "/cli/migrate", label: "migrate" },
  { href: "/cli/export", label: "export" },
  { href: "/cli/workflows", label: "Workflows" },
  { href: "/cli/ci", label: "CI & Automation" },
  { href: "/cli/reference", label: "Reference" },
  { href: "/packages", label: "Package Map", hint: "Every package" },
  { href: "/packages/core", label: "@theme-kit/core" },
  { href: "/packages/react", label: "@theme-kit/react" },
  { href: "/packages/next", label: "@theme-kit/next" },
  { href: "/packages/vue", label: "@theme-kit/vue" },
  { href: "/packages/svelte", label: "@theme-kit/svelte" },
  { href: "/packages/solid", label: "@theme-kit/solid" },
  { href: "/packages/angular", label: "@theme-kit/angular" },
  { href: "/packages/web", label: "@theme-kit/web" },
  { href: "/packages/tailwind", label: "@theme-kit/tailwind" },
  { href: "/packages/astro", label: "@theme-kit/astro" },
  { href: "/packages/nuxt", label: "@theme-kit/nuxt" },
  { href: "/packages/remix", label: "@theme-kit/remix" },
  { href: "/packages/cli", label: "@theme-kit/cli" },
  { href: "/packages/devtools", label: "@theme-kit/devtools" },
  { href: "/api-reference", label: "API Reference", hint: "Generated API docs" },
  { href: "/devtools", label: "DevTools", hint: "Inspect and debug themes" },
  { href: "/troubleshooting", label: "Troubleshooting", hint: "Common issues" },
  { href: "/known-limitations", label: "Known Limitations", hint: "Honest boundaries" },
  { href: "/blog", label: "Blog" },
  { href: "/roadmap", label: "Roadmap", hint: "What's next" },
];
