/**
 * Section-level search data for JSX-built pages that have no markdown source.
 * Generated by extracting each page's PageHeader description and
 * SectionHeading titles/descriptions; curated alongside lib/docs-routes.ts.
 * Merged into the search index by lib/search.ts so section keywords on these
 * pages are findable, not just the sidebar hint.
 */
export type PageSectionEntry = {
  route: string;
  intro?: string;
  sections: { title: string; desc?: string }[];
};

export const PAGE_SECTIONS: PageSectionEntry[] = [
  {
    route: "/get-started",
    sections: [
      { title: "How are you building?" },
      { title: "Your first Theme Kit application" },
    ],
  },
  {
    route: "/choose-package",
    intro: "Start from what you're building. Every framework package pulls the core runtime, so you install the integration, not everything at once.",
    sections: [
      { title: "Pick your entry point" },
      { title: "Common combinations" },
      { title: "Still unsure?" },
    ],
  },
  {
    route: "/tokens/code",
    sections: [
      { title: "Define code tokens in your theme", desc: "All 22 code tokens live under tokens.code and resolve alongside colors, spacing, typography, etc." },
      { title: "Code token reference", desc: "Complete reference of every code token, its purpose, and the CSS variable it produces." },
      { title: "Enable code tokens in your app", desc: "Map theme code tokens to your syntax highlighter's CSS variables." },
      { title: "Best practices", desc: "Practical tips for working with code tokens." },
      { title: "Go deeper", desc: "Tokens are the input — here's what consumes them." },
    ],
  },
  {
    route: "/sunrise-sunset",
    sections: [
      { title: "How it works", desc: "One scheduling engine in core; frameworks only add native reactivity." },
      { title: "Setup", desc: "Pass `scheduled` to your provider (or module). One block, no per-framework solar engine." },
      { title: "Read & control the schedule", desc: "The accessor exposes the same contract everywhere: reactive `enabled`, `active`, `status`, `sunrise`, `sunset`, `nextTransition`, `timeZone`, `latitude`, `longitude`, plus `enable()` / `disable()` / `set()`." },
      { title: "Options", desc: "Every `scheduled` option, and the runtime `set()` method for repositioning." },
      { title: "Schedule vs. manual override", desc: "Exact semantics, so there are no surprises when a user picks a theme while the schedule is on." },
      { title: "What's next", desc: "Now that the app follows the sun, explore related capabilities." },
    ],
  },
  {
    route: "/migration",
    sections: [
      { title: "When to migrate", desc: "Use migrateTheme when you bump a version, hit a breaking change, or adopt a new token schema." },
      { title: "migrateTheme(theme, options)", desc: "migrateTheme(theme, options) reads meta.version, walks the migration chain, and returns an updated theme." },
      { title: "registerMigration({ from, to, remapColors?, migrate? })", desc: "registerMigration adds a step between two versions. Each step can carry a color remap table, a custom migrate function, or both." },
      { title: "Multi-step migration", desc: "When a theme is several versions behind, the engine walks every intermediate step automatically." },
      { title: "remapColors vs migrate", desc: "Use remapColors for simple renames. Use migrate when the transformation requires logic or structural changes." },
      { title: "CI integration", desc: "Catch outdated themes in CI before they ship. Run migrateTheme against every theme and fail the build if any are behind." },
    ],
  },
  {
    route: "/persistence",
    sections: [
      { title: "How persistence works", desc: "The default behavior stores only the user's selection (mode + family), not the full theme definition." },
      { title: "Storage keys", desc: "Customize the key under which the selection is stored to avoid collisions on shared origins." },
      { title: "Custom adapters", desc: "Any object that implements ThemeSelectionPersistenceAdapter can be plugged in." },
      { title: "Server-side persistence", desc: "Use HTTP cookies to persist selection across environments where localStorage is unavailable." },
      { title: "Disabling persistence", desc: "Pass null to the persistence option or omit the plugin entirely." },
      { title: "Persistence vs. sync", desc: "Persistence and broadcast solve different problems — they are complementary, not competing." },
    ],
  },
  {
    route: "/multi-window-sync",
    sections: [
      { title: "The Problem", desc: "Each browser tab runs its own runtime instance — without synchronization the selections drift apart." },
      { title: "BroadcastChannel", desc: "BroadcastChannel is the default transport — messages reach every same-origin tab without touching the DOM." },
      { title: "StorageEvent Fallback", desc: "For environments where BroadcastChannel is blocked (some WebView contexts, older browsers), a localStorage-based fallback keeps everything in sync." },
      { title: "Cross-Tab Persistence", desc: "localStorage is the persistence layer — the sync adapters react to storage changes and push updates into the runtime." },
      { title: "Setup in Every Framework", desc: "A thin hook or composable wraps the adapter lifecycle — mount creates, unmount destroys." },
      { title: "Custom Channels", desc: "Different channel names create isolated sync scopes — admin and storefront can maintain independent theme selections." },
    ],
  },
  {
    route: "/token-resolution",
    sections: [
      { title: "Token references", desc: "Reference tokens let one token alias another, keeping your palette DRY and your overrides shallow." },
      { title: "Expressions", desc: "Numeric expressions let you compute spacing, sizes, and other values inline without a separate build step." },
      { title: "Derived colors", desc: "Derived tokens compute values like contrast-safe foreground colors from a background, no manual pairing needed." },
      { title: "Resolution order", desc: "The resolver runs a strict pipeline so every token category is fully resolved before the next." },
      { title: "API Reference", desc: "The resolve module exports focused utilities you can use individually or compose into your own pipeline." },
    ],
  },
  {
    route: "/plugins",
    sections: [
      { title: "What is a Plugin?", desc: "A plugin is an object with a name, an optional version and priority, and any combination of lifecycle hooks." },
      { title: "Plugin Hooks", desc: "Lifecycle hooks fire at predictable points during the theme runtime's lifetime." },
      { title: "Token Transforms", desc: "Transform tokens before they reach the DOM — override, augment, or remap any token path." },
      { title: "Priority & Ordering", desc: "The priority field controls plugin execution order — lower values run first." },
      { title: "Runtime Integration", desc: "Manage plugins at runtime with the PluginManager — register, look up, remove, and destroy." },
      { title: "Full Example", desc: "A complete plugin that dispatches custom events on theme changes and boosts contrast on dark tokens." },
    ],
  },
  {
    route: "/dom-adapters",
    sections: [
      { title: "What are DOM Adapters?", desc: "Adapters subscribe to the theme store and apply changes to the DOM. Each adapter owns one concern — CSS variables, attributes, system preference — so they can be composed independently." },
      { title: "CSS Variables Binding", desc: "createCSSVariablesBinding() writes theme tokens as --theme-color-* custom properties on :root, enabling any CSS in the page to reference theme values." },
      { title: "DOM Attribute Binding", desc: "createDOMBinding() writes identity attributes so CSS selectors and JavaScript can react to the active theme without reading the store." },
      { title: "System Theme Binding", desc: "createSystemThemeBinding() listens to the OS color scheme preference and automatically swaps between a light and dark theme." },
      { title: "Scoped Theme Binding", desc: "createScopedThemeBinding() isolates a subtree to its own theme, independent of the page-level provider." },
      { title: "Transition Binding", desc: "The diff → plan → animate pipeline is the internal engine that makes theme transitions smooth. The CSS variables binding owns it — other adapters opt in through the shared View Transition." },
      { title: "Disabling Adapters", desc: "Adapters can be selectively disabled. Skip DOM attributes entirely, suppress CSS variable output, or turn off transitions for specific bindings." },
    ],
  },
  {
    route: "/vanilla",
    sections: [
      { title: "Why Vanilla?", desc: "When your page is a plain HTML file, a server-rendered template, or a framework that Theme Kit doesn't ship an adapter for." },
      { title: "The ThemeKit class", desc: "Import the class, pass your options, and the instance handles everything — DOM binding, persistence, and event emission." },
      { title: "Reading the active theme", desc: "Synchronous getters expose the active theme, its mode, and its family — plus a reactive event system." },
      { title: "Switching themes", desc: "Switch mode, switch family, or toggle — every change is persisted and emits the appropriate event." },
      { title: "DOM binding", desc: "ThemeKit automatically writes CSS custom properties and a data-theme attribute to the target element. You can also read or apply them manually." },
      { title: "Persistence", desc: "Mode and family are persisted to localStorage on every change and automatically restored when a new instance is created." },
      { title: "Full HTML example", desc: "A complete HTML page with a working theme switcher — save it as index.html and open it in a browser." },
    ],
  },
  {
    route: "/vite-plugin",
    sections: [
      { title: "Why a Vite Plugin?", desc: "Build-time injection eliminates the flash-of-wrong-theme without client-side workarounds." },
      { title: "Setup", desc: "Drop the plugin into your Vite config alongside your framework plugin." },
      { title: "What It Does", desc: "The plugin reads your theme definitions and produces an inline script that sets the correct theme before paint." },
      { title: "Options", desc: "Full control over which themes are bundled, the default selection, and the storage key." },
      { title: "SSR Integration", desc: "For SSR frameworks, mirror the same bootstrap in server-rendered HTML to avoid a hydration mismatch." },
    ],
  },
  {
    route: "/troubleshooting",
    sections: [
      { title: "Flash of Unstyled Content (FOUC)", desc: "A flash of unstyled or incorrectly-styled content before the theme loads." },
      { title: "Theme Not Persisting", desc: "The selected theme resets after a page reload or closes and reopens." },
      { title: "or are not reflecting the active theme.\" > CSS Variables Not Updating" },
      { title: "Hydration Mismatch", desc: "Next.js or React reports a hydration mismatch warning in the console." },
      { title: "Theme Flicker on Navigation", desc: "The theme briefly flashes to the default on client-side route changes." },
      { title: "Scoped Theme Not Working", desc: "A ThemeScope has no visible effect on the targeted subtree." },
      { title: "Transitions Not Animating", desc: "Theme switches are instant instead of animated." },
      { title: "Build Error: Module Not Found", desc: "Your bundler throws a Module Not Found error for @theme-kit packages." },
      { title: "Accessibility Audit Failing", desc: "Automated accessibility audits flag color contrast failures in your theme." },
      { title: "Multi-Window Out of Sync", desc: "Changing the theme in one tab does not update other open tabs." },
    ],
  },
];
